const wishlistActionTypes = {
  ADD_ITEM_TO_WISHLIST: "ADD_ITEM_TO_WISHLIST",
  CLEAR_ITEM_FROM_WISHLIST: "CLEAR_ITEM_FROM_WISHLIST",
  REMOVE_ITEM_FROM_WISHLIST: "REMOVE_ITEM_FROM_WISHLIST",
};

export default wishlistActionTypes;
