const SHOP_DATA = {
  hats: {
    id: 1,
    title: "Hats",
    routeName: "hats",
    items: [
      {
        id: 1,
        name: "Beige Cap",
        imageUrl: "https://source.unsplash.com/K7ADMFTwxac/600x900",
        price: 25,
      },
      {
        id: 2,
        name: "Blue Beanie",
        imageUrl: "https://source.unsplash.com/uED_eXXHNuQ/600x900",
        price: 18,
      },
      {
        id: 3,
        name: "Dark Grey Cowboy",
        imageUrl: "https://source.unsplash.com/Wxs5zGQ5Oyw/600x900",
        price: 35,
      },
      {
        id: 4,
        name: "Pink Beenie",
        imageUrl: "https://source.unsplash.com/1SdQor4_bec/600x900",
        price: 25,
      },
      {
        id: 5,
        name: "Beige Fedora",
        imageUrl: "https://source.unsplash.com/ybzutrQy4s/600x900",
        price: 18,
      },
      {
        id: 6,
        name: "Light Brown Sun Hat",
        imageUrl: "https://source.unsplash.com/3eebt4Xsg_c/600x900",
        price: 14,
      },
      {
        id: 7,
        name: "Light Brown Sun Hat",
        imageUrl: "https://source.unsplash.com/GOR2kYIPT6E/600x900",
        price: 18,
      },
      {
        id: 8,
        name: "Brown Sun Hat",
        imageUrl: "https://source.unsplash.com/bhLMUIlIhxk/600x900",
        price: 14,
      },
      {
        id: 9,
        name: "White Beenie",
        imageUrl: "https://source.unsplash.com/8E6R5ofg2hg/600x900",
        price: 16,
      },
    ],
  },
  sneakers: {
    id: 2,
    title: "Sneakers",
    routeName: "sneakers",
    items: [
      {
        id: 10,
        name: "Nike Air",
        imageUrl: "https://source.unsplash.com/EJTjetc8tPs/600x900",
        price: 220,
      },
      {
        id: 11,
        name: "Adidas Yeezy",
        imageUrl: "https://source.unsplash.com/dwKiHoqqxk8/600x900",
        price: 280,
      },
      {
        id: 12,
        name: "Black Converse",
        imageUrl: "https://source.unsplash.com/1BI-ar91C7U/600x900",
        price: 110,
      },
      {
        id: 13,
        name: "Air Jordan Limited",
        imageUrl: "https://source.unsplash.com/q35zYDIJSjo/600x900",
        price: 160,
      },
      {
        id: 14,
        name: "Maroon Vans",
        imageUrl: "https://source.unsplash.com/a-QH9MAAVNI/600x900",
        price: 160,
      },
      {
        id: 15,
        name: "Nike Army Green High Tops",
        imageUrl: "https://source.unsplash.com/qLs4WYXqLNY/600x900",
        price: 160,
      },
      {
        id: 16,
        name: "AirForce Limited",
        imageUrl: "https://source.unsplash.com/PqbL_mxmaUE/600x900",
        price: 190,
      },
      {
        id: 17,
        name: "Timberlands",
        imageUrl: "https://source.unsplash.com/Br_wYlGiYlw/600x900",
        price: 200,
      },
    ],
  },
  jackets: {
    id: 3,
    title: "Jackets",
    routeName: "jackets",
    items: [
      {
        id: 18,
        name: "Red Jacket",
        imageUrl: "https://source.unsplash.com/1Jivk4tRo_s/1200x700",
        price: 125,
      },
      {
        id: 19,
        name: "Black Jacket",
        imageUrl: "https://source.unsplash.com/qRs4h6eRhNI/1200x700",
        price: 90,
      },
      {
        id: 20,
        name: "Grey Trench Coat",
        imageUrl: "https://source.unsplash.com/H1Ufu8QD5NY/1200x700",
        price: 90,
      },
      {
        id: 21,
        name: "Brown Trench",
        imageUrl: "https://source.unsplash.com/txtUr7HOKrc/1200x700",
        price: 165,
      },
      {
        id: 22,
        name: "White Trench",
        imageUrl: "https://source.unsplash.com/PSOvH4dfrmg/600x900",
        price: 185,
      },
    ],
  },
  women: {
    id: 4,
    title: "Women's",
    size: "large",
    routeName: "womens",
    items: [
      {
        id: 23,
        name: "Striped Top",
        imageUrl: "https://source.unsplash.com/ccNojE60GkE/600x900",
        price: 125,
      },
      {
        id: 24,
        name: "Colourful Blouse",
        imageUrl: "https://source.unsplash.com/hb8v-SZm7VY/600x900",
        price: 60,
      },
      {
        id: 25,
        name: "Black Dress",
        imageUrl: "https://source.unsplash.com/pXi1S2uKG5I/600x900",
        price: 80,
      },
      {
        id: 26,
        name: "Plain White Sweater",
        imageUrl: "https://source.unsplash.com/2OgHmIzpQ5U/600x900",
        price: 80,
      },
      {
        id: 27,
        name: "Brown Pants",
        imageUrl: "https://source.unsplash.com/KA3BpKEI0kg/600x900",
        price: 45,
      },
      {
        id: 28,
        name: "Colourful Striped Sweater",
        imageUrl: "https://source.unsplash.com/WuZ7poeM21Y/600x900",
        price: 135,
      },
      {
        id: 29,
        name: "Floral Skirt",
        imageUrl: "https://source.unsplash.com/H2LI3hBc2xw/600x900",
        price: 140,
      },
      {
        id: 30,
        name: "Black Jacket",
        imageUrl: "https://source.unsplash.com/8Zv6hOS_STE/600x900",
        price: 20,
      },
      {
        id: 31,
        name: "Long Brown Maxi Dress",
        imageUrl: "https://source.unsplash.com/V6Hyq-r3cgw/600x900",
        price: 120,
      },
      {
        id: 32,
        name: "Yellow Jacket",
        imageUrl: "https://source.unsplash.com/bWUOx0SaSAk/600x900",
        price: 60,
      },
      {
        id: 33,
        name: "Beige Shorts",
        imageUrl: "https://source.unsplash.com/pONwcn4IcVU/600x900",
        price: 30,
      },
      {
        id: 34,
        name: "Long Yellow Jacket",
        imageUrl: "https://source.unsplash.com/QPNaz7qS16c/600x900",
        price: 80,
      },
      {
        id: 35,
        name: "White Tank Top",
        imageUrl: "https://source.unsplash.com/pU4J5VFnqCQ/600x900",
        price: 30,
      },
      {
        id: 36,
        name: "Brown Jacket",
        imageUrl: "https://source.unsplash.com/OJP-jz7iuVU/600x900",
        price: 120,
      },
      {
        id: 37,
        name: "Color Jacket",
        imageUrl: "https://source.unsplash.com/ODG3C3udpsc/600x900",
        price: 80,
      },
      {
        id: 38,
        name: "Transparent Boots",
        imageUrl: "https://source.unsplash.com/QHGcADeeT00/600x900",
        price: 220,
      },
      {
        id: 39,
        name: "Floral blue Heels",
        imageUrl: "https://source.unsplash.com/E-0ON3VGrBc/600x900",
        price: 80,
      },
      {
        id: 40,
        name: "Hot Pink Heels",
        imageUrl: "https://source.unsplash.com/jMlig2nx1-Y/600x900",
        price: 220,
      },
      {
        id: 41,
        name: "High-heel Blocks",
        imageUrl: "https://source.unsplash.com/ebkqnPGc5iw/600x900",
        price: 120,
      },
      {
        id: 42,
        name: "White Boots",
        imageUrl: "https://source.unsplash.com/wwburg1nAvg/600x900",
        price: 200,
      },
      {
        id: 43,
        name: "Floral Skirt",
        imageUrl: "https://source.unsplash.com/H2LI3hBc2xw/600x900",
        price: 120,
      },
    ],
  },
  men: {
    id: 5,
    title: "Men's",
    size: "large",
    routeName: "mens",
    items: [
      {
        id: 44,
        name: "Striped T-shirt",
        imageUrl: "https://source.unsplash.com/cYSRncVxE44/600x900",
        price: 29.99,
      },
      {
        id: 45,
        name: "Checkered Shirt",
        imageUrl: "https://source.unsplash.com/J7Cf1Gch49E/600x900",
        price: 89.99,
      },
      {
        id: 46,
        name: "Grey Jacket",
        imageUrl: "https://source.unsplash.com/idoedMZ732E/600x900",
        price: 124.99,
      },
      {
        id: 47,
        name: "White T-shirt",
        imageUrl: "https://source.unsplash.com/CtYWLXbPoW4/600x900",
        price: 69.99,
      },
      {
        id: 48,
        name: "Jean Long Sleeve",
        imageUrl: "https://source.unsplash.com/xTttn9OGJr8/600x900",
        price: 125,
      },
      {
        id: 49,
        name: "Grey Long Sleeve",
        imageUrl: "https://source.unsplash.com/_J3X-g-2KKc/600x900",
        price: 99.99,
      },
      {
        id: 50,
        name: "White Long Jacket",
        imageUrl: "https://source.unsplash.com/PSOvH4dfrmg/600x900",
        price: 165,
      },
      {
        id: 51,
        name: "Red Hoodie",
        imageUrl: "https://source.unsplash.com/gfTLohGEssA/600x900",
        price: 75,
      },
      {
        id: 52,
        name: "Beige Jacket",
        imageUrl: "https://source.unsplash.com/txtUr7HOKrc/600x900",
        price: 139.99,
      },
      {
        id: 53,
        name: "Stylish Hoodie",
        imageUrl: "https://source.unsplash.com/cpsYx4TYBhg/600x900",
        price: 125,
      },
      {
        id: 54,
        name: "Jungle Green Bomber",
        imageUrl: "https://source.unsplash.com/bNdh9AUVifM/600x900",
        price: 65,
      },
      {
        id: 55,
        name: "Black Leather Jacket",
        imageUrl: "https://source.unsplash.com/6UEyVsw_1lU/600x900",
        price: 175,
      },
      {
        id: 56,
        name: "Denim Long Sleeve",
        imageUrl: "https://source.unsplash.com/z-JKxfzYM7U/600x900",
        price: 199.99,
      },
      {
        id: 57,
        name: "Slim Fit Pants",
        imageUrl: "https://source.unsplash.com/GUTUCKSU1jU/600x900",
        price: 75,
      },
      {
        id: 58,
        name: "Red Bubble Jacket",
        imageUrl: "https://source.unsplash.com/3aprZ1mflDo/600x900",
        price: 65,
      },
      {
        id: 59,
        name: "Grey Long Sleeve",
        imageUrl: "https://source.unsplash.com/_J3X-g-2KKc/600x900",
        price: 85,
      },
      {
        id: 60,
        name: "Dark Grey T-shirt",
        imageUrl: "https://source.unsplash.com/GQG56fYaejg/600x900",
        price: 45,
      },
      {
        id: 61,
        name: "Brown Shearling",
        imageUrl: "https://source.unsplash.com/ifYt0sKdJYk/600x900",
        price: 99.99,
      },
      {
        id: 62,
        name: "Grey Sleevless Top",
        imageUrl: "https://source.unsplash.com/Py8F6-hRn5o/600x900",
        price: 125,
      },
      {
        id: 63,
        name: "Brown Timberland Boots",
        imageUrl: "https://source.unsplash.com/1YET7ksfk9c/600x900",
        price: 155,
      },
    ],
  },
};

export default SHOP_DATA;
